#-----------------------------------------------------------------------------
#  Configuration
#-----------------------------------------------------------------------------
COMPONENT_NAME = "hellomars"

IMPORTED_COMPONENTS = [
("#imported/esp-idf-master", 'https://github.com/espressif/esp-idf.git', "master"),
("#imported/tinypy-master",  'https://github.com/eyob-boye/tinypy.git',  "master"),
(None,                       '#../..', None)
]


#-----------------------------------------------------------------------------
#  Call shared common script
#-----------------------------------------------------------------------------
SConscript(MakooCommonScript("esp_idf"),
           exports=['COMPONENT_NAME', 'IMPORTED_COMPONENTS'])

